### ISSUE TITLE
Handle no hostname

### ISSUE THREAD

**Issue by SecT0uch** [marduc812/vscode-nmap-peek#4]
I'm getting a `Cannot read properties of undefined (reading 'hostname')`

The blocks in the nmap output are like this:
```xml
<hostnames>
</hostnames>
```

**Comment by marduc812** [comment]
Hi @SecT0uch ,

Do you think you could share the nmap scan with me?
an empty `hostnames` tag shouldn't be a problem. I opened 3 nmap scans that I have with empty hostnames and they were rendering as expected. 
![empty hostnames](https://user-images.githubusercontent.com/5909985/232113747-94916925-b87b-49d4-a18c-8fc1f96c30d3.png)

**Comment by SecT0uch** [comment]
Unfortunately I can't share this one in particular but by command line looked like: `sudo nmap -sV -sC -iL external-hosts.txt -p- -oX external-hosts.xml -v --defeat-rst-ratelimit`.
I will see if I can reproduce against a VM and let you know

**Comment by marduc812** [comment]
I reproduced the error and fixed it!
@SecT0uch , thanks for your feedback!
In a few minutes the latest version should be online, so you can confirm that it is fixed.

**Comment by SecT0uch** [comment]
Awesome!

Thanks again
